fix: pg is having trouble to import, switched to postgres
```
SyntaxError: Missing 'default' export in module '/app/node_modules/pg/lib/index.js'.
      at newLoader (/app/node_modules/drizzle-kit/bin.cjs:14317:13)
      at <anonymous> (/app/node_modules/drizzle-kit/bin.cjs:18488:20)
```